### ISSUE TITLE
Cannot pass multiple flags to Markly.parse and documentation is out of date

### ISSUE THREAD

**Issue by dhnaranjo** [ioquatix/markly#2]
Example scenario is adding `SMART` parser option.

Documentation says `Markly.parse(phrase, :SMART)`, get an arity error, expected 1 got 2.

`Markly.parse(phrase, flags: Markly::SMART)` will get me what I need, but I am not clear on how to pass multiple options, as `Markly.parse(phrase, flags: [Markly::SMART])` throws `wrong argument type Array (expected Integer) (TypeError)`.

Edit: Seems to work if you, for example, `Markly.parse(content, flags: [Markly::SMART, Markly::NO_BREAKS].sum)` This accurate?

**Comment by bradgessler** [comment]
I'm seeing the same thing, but I haven't verified if the sum of those constants get the desired output.

@ioquatix do you have a preference for either fixing the docs to read as @dhnaranjo wrote above ... or would you prefer the documented `Markly.parse("foo", [:SMART, NO_BREAKS])` syntax that does something like `flags.map { Markly.const_get _1 }.sum` inside the `Markly.parse method`?

I can open a PR either way.

**Comment by ioquatix** [comment]
Sorry this was not clearly explained, let's update the documentation. To give multiple flags, use the `|` operation, e.g.

```ruby
Markey.parse(..., flags: Markly::SMART | Markey::NO_BREAKS)
```

**Comment by ioquatix** [comment]
Looking at `bin/markly` I have done really just the bare minimum to extend the AST. I'll need to do more extensive work to bring other parts of the gem up to scratch.

**Comment by ioquatix** [comment]
I took a first pass at this: https://github.com/ioquatix/markly/commit/f51135d7ac4f6e2e6f898da225941d8292926341 however please feel free to make a PR for further improvements.

**Comment by bradgessler** [comment]
Thanks! The docs are much better and I can verify that it all works.

**Comment by dhnaranjo** [comment]
Yeah this is solid, thanks.
