### ISSUE TITLE
Markdown renderer

### ISSUE THREAD

**Issue by technicalpickles** [ioquatix/markly#6]
I'm trying to do some manipulate some existing markdown documents, and then output the updated file. I'm not seeing a way to do that currently.

There is a html renderer, so I suppose it's possible to render to HTML, then try to parse that back as markdown. It seems there should be a more direct way to do it though.

**Comment by ioquatix** [comment]
Use `to_markdown` on the parsed node.

```ruby
require 'markly'
Markly.parse("Hello *World*").to_markdown
# => "Hello *World*\n"
```
